---
title: "03: Running Your Model"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{03: Initializing Your Model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Overview

The `*car()` functions (`eucar()`, `ucar()`, `mcar()`, `mstcar()`) build the necessary features needed to run `RSTr` and places them in the specified directory. In this vignette, we will talk in detail about each argument and how to use them.

## Arguments of the `*car()` function

All `*car()` functions provide several arguments:

-   `name`: The name of the folder your model information lives in;

-   `data`: The `list` object containing the event `Y` and population `n` data. For more information on `data` setup, read `vignette("RSTr-event")`;

-   `adjacency`: The adjacency structure for your event and population data. For more information on adjacency structure setup, read `vignette("RSTr-adjacency")`;

-   `dir`: The directory where the model folder lives. By default, this saves into your temporary directory, so the model information will be lost after the R session ends. Should you want to save your model to be analyzed at a later date or ensure that your samples are intact if R crashes during runtime, specify a different directory;

-   `seed`: Allows the user to specify the random seed used for replication purposes;

-   `perc_ci`: A number between 0 and 1 which specifies the desired credible interval to use when calculating the relative precision of estimates. By default, set to 0.95;

-   `iterations`: The number of iterations to run the model for;

-   `show_plots`: If set to `FALSE`, hides traceplots during model execution;

-   `verbose`: If set to `FALSE`, hides the progress bar and messages in the console;

-   `ignore_checks`: If set to `TRUE`, skips model validation;

-   `method`: Chooses whether the event data is either Binomial (`"binomial"`) or Poisson (`"poisson"`) distributed. By default, `RSTr` uses Binomial updates for event data;

-   `impute_lb`: Specifies a lower bound for imputed data for event information that is missing or suppressed;

-   `impute_ub`: Specifies an upper bound for imputed data for event information that is missing or suppressed;

-   `initial_values`: This is a `list` of initial values for each parameter. This can be specified by the user or generated by default; and

-   `priors`: This is a `list` of all prior information for each parameter. This can be specified by the user or generated by default.

Most of these arguments are not needed, as the model has defaults for most arguments. `eucar()` and `mstcar()` have additional arguments only used by them:

-   `A`: In the EUCAR model, describes the limit of the smoothing intensity between regions;

-   `m0`: In the EUCAR model, specifies the baseline neighbor count; and

-   `update_rho`: In the MSTCAR model, allows for updates of the temporal correlation parameter `rho`. By default, `RSTr` does not update `rho`.

If you run into errors when trying to initialize your model, read `vignette("RSTr-troubleshoot")`. Below, we will go into detail regarding what each argument does specifically and what to keep in mind when setting these values.

### The `initial_values` argument

`initial_values` is a `list` specifying the starting values for each parameter of the model. Each parameter can have an initial value specified. Here are the possible initial value parameters for the MSTCAR model:

-   `lambda`: The estimated spatially smoothed rate for each region-group-time. `lambda` is an `array` of real numbers with dimensions `num_region x num_group x num_time`. Has support `(0, 1)` for `method = "binomial"` and support `(0, Inf)` for `method = "poisson";

-   `beta`: The mean rate for each island-group-year on a logit- or log-transformed scale. Islands are sets of regions that exclusively share adjacency information. For example, in `miadj`, there are two islands that represent the counties of the Upper Peninsula and the Lower Peninsula. These islands don't touch each other, and thus don't share adjacency information. Therefore, each island is assigned its own `beta`. `beta` is an `array` of real numbers with dimensions `num_island x num_group x num_time`;

-   `Z`: The spatiotemporal random effects. These are the parameters that induce smoothing on the counties, with the intensity of the smoothing dictated by the spatial covariance matrices `G`. `Z` is an `array` of real numbers with dimensions `num_region x num_group x num_time`;

-   `G`: The spatial covariance matrices. This parameter determines the intensity of the spatial smoothing performed by `Z` and represents the strength of the relationship between each group in a given time period. `G` is an `array` of temporally-evolving positive-definite symmetric matrices with dimensions `num_group x num_group x num_time`;

-   `rho`: The temporal correlation. This parameter decides the strength of the relationship between values in time period `t` to values in time period `t-1`. It is a `matrix` of size `num_group x 1` of real numbers with support `[0,1]`;

-   `tau2`: The non-spatial variance. This parameter picks up any variance in values of `lambda` for each group. It is a `matrix` of size `num_group x 1` of positive real numbers; and

-   `Ag`: The general spatial covariance matrix. This parameter describes the overall relationship between groups across the entire model and is used in the prior distribution for the matrices in `G`. `Ag` is a positive-definite symmetric matrix with dimensions `num_group x num_group`.

Note that you don't have to specify `initial_values` for *all* parameters if you only want to specify some of them - any undefined `initial_values` will be defined by the default values. For example, you can specify only the initial values for `lambda` and all other values will be generated on their own. However, if one value is specified for a certain parameter in `initial_values`, all values must be specified for that parameter in `initial_values`: you cannot, for example, define initial values for just one year of `lambda`. Finally, any values included in your `initial_values` list that aren't aligned with the above names will be ignored.

### The `priors` argument

`priors` behaves similar to `initial_values`, except that it contains all information related to parameter priors. The following are all priors used in the MSTCAR model:

-   `Ag_scale` and `Ag_df`: These are the scale and degrees of freedom priors used with [Wishart-distributed](https://en.wikipedia.org/wiki/Wishart_distribution) random variable `Ag`. `Ag_scale` is a positive-definite symmetric matrix and `Ag_df` is a `double` of at least size `num_group`;

-   `G_scale` and `G_df`: These are the scale and degrees of freedom priors used with [Inverse-Wishart distributed](https://en.wikipedia.org/wiki/Inverse-Wishart_distribution) matrix slices of random variable `G`. `G_scale` is a positive-definite symmetric matrix and `G_df` is a `double` of at least size `num_group`;

-   `tau_a` and `tau_b`: These are the rate and scale priors used with [Inverse-Gamma distributed](https://en.wikipedia.org/wiki/Inverse-gamma_distribution) random variable `tau2`. `tau_a` and `tau_b` must both be positive real numbers;

-   `rho_a` and `rho_b`: These are the shape priors used with [Beta-distributed](https://en.wikipedia.org/wiki/Beta_distribution) random variable `rho`. `rho_a` and `rho_b` must both be positive real numbers;

-   `lambda_sd`: An array of positive real numbers describing the candidate standard deviation in the Metropolis update for the estimated rates `lambda`. These values will be adaptively updated at the start of each batch; and

-   `rho_sd`: A vector of positive real numbers describing the candidate standard deviation in the Metropolis update for the temporal correlation `rho`. These values will be adaptively updated at the start of each batch. Note that this is only used if `update_rho = TRUE`.

By default, most of these priors are relatively non-informative. Similar to `initial_values`, you don't have to specify priors for *all* parameters if you only want to specify some of them - any undefined priors will be defined by the default values. Any values included in `priors` that aren't aligned with the above names will be ignored.

### The `method` argument

`method` offers two values: `"binomial"` and `"poisson"`. These values determine how the data is transformed and how the `lambda` Metropolis update is performed: `"binomial"` treats the event data as Binomial-distributed and `"poisson"` treats the event data as Poisson-distributed. Depending on your use case, you'll want to choose between the two: for example, if you are working with very small mortality rates, `"poisson"` will work well, but if you are working with birth rates, for example, then `"binomial"` will work better. Note that `"binomial"` works in most general use cases and `"poisson"` only works well for datasets with small rates under approximately 1%.

### `m0` and `A`

`m0` and `A` are two components that determine the intensity of the smoothing of restricted CAR models. `m0` should be a positive scalar, and the size of `A` is dependent on the group/time structure of your data: `A` will be a positive scalar for region-only models, a `vector` of size `num_group` for region-group models, and a matrix of size `num_group` x `num_time` for region-group-time models. Note, however, that these informativeness restriction measures are currently only developed for the UCAR model, and restrictions for more complex models will be added to the `RSTr` package as their respective methods are developed.

### The `update_rho` argument

In the MSTCAR model, `update_rho` is a `logical` that specifies whether to calculate estimates for the temporal correlation `rho`. By default, it is set to `FALSE`. In empirical testing, this estimate was found to not be very sensitive to changes when specified prudently and also increases runtime by an order of magnitude due to its complexity.

### The `seed` argument

Because of the stochastic nature of Bayesian inference and the inherent instability of the MSTCAR model, replicability is extremely important. `seed` allows the user to specify a seed for generating similar estimates, set by default to `1234`.

### The `ignore_checks` argument

As development continues on `RSTr`, there are occasions where the checks performed on the inputs of `*car()` throw an error, even though you may be certain that all of your inputs are behaving as expected. To override the checks, you can use the `ignore_checks` argument. Set this to `TRUE` to skip this step.

## Closing Thoughts

Initialization is one of the most important steps of running the model, as it's where virtually all choices regarding the model are made. In this vignette, we explored each argument of the `*car()` functions and how to appropriately choose values for each argument.