// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_regs
arma::cube get_regs(const arma::cube& arr, const arma::uvec& ind);
RcppExport SEXP _RSTr_get_regs(SEXP arrSEXP, SEXP indSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type ind(indSEXP);
    rcpp_result_gen = Rcpp::wrap(get_regs(arr, ind));
    return rcpp_result_gen;
END_RCPP
}
// get_subregs
arma::vec get_subregs(const arma::cube& arr, const arma::uvec& ind, const arma::uword& grp, const arma::uword& time);
RcppExport SEXP _RSTr_get_subregs(SEXP arrSEXP, SEXP indSEXP, SEXP grpSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type ind(indSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type grp(grpSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_subregs(arr, ind, grp, time));
    return rcpp_result_gen;
END_RCPP
}
// get_grp
arma::vec get_grp(const arma::cube& arr, const arma::uword& reg, const arma::uword& time);
RcppExport SEXP _RSTr_get_grp(SEXP arrSEXP, SEXP regSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type reg(regSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_grp(arr, reg, time));
    return rcpp_result_gen;
END_RCPP
}
// get_row
arma::vec get_row(const arma::cube& arr, const arma::uword& grp, const arma::uword& time);
RcppExport SEXP _RSTr_get_row(SEXP arrSEXP, SEXP grpSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type grp(grpSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_row(arr, grp, time));
    return rcpp_result_gen;
END_RCPP
}
// Sig_eta_i
arma::field<arma::mat> Sig_eta_i(const arma::cube& G, const arma::vec& rho);
RcppExport SEXP _RSTr_Sig_eta_i(SEXP GSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(Sig_eta_i(G, rho));
    return rcpp_result_gen;
END_RCPP
}
// Sig_eta
arma::field<arma::mat> Sig_eta(const arma::field<arma::mat>& Sein);
RcppExport SEXP _RSTr_Sig_eta(SEXP SeinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Sein(SeinSEXP);
    rcpp_result_gen = Rcpp::wrap(Sig_eta(Sein));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rmvnorm
arma::mat cpp_rmvnorm(const arma::vec& mean, const arma::mat& covar);
RcppExport SEXP _RSTr_cpp_rmvnorm(SEXP meanSEXP, SEXP covarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covar(covarSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rmvnorm(mean, covar));
    return rcpp_result_gen;
END_RCPP
}
// geteig
arma::mat geteig(const arma::mat& covar);
RcppExport SEXP _RSTr_geteig(SEXP covarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type covar(covarSEXP);
    rcpp_result_gen = Rcpp::wrap(geteig(covar));
    return rcpp_result_gen;
END_RCPP
}
// update_beta_m
arma::mat update_beta_m(List inits, List spatial_data);
RcppExport SEXP _RSTr_update_beta_m(SEXP initsSEXP, SEXP spatial_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(update_beta_m(inits, spatial_data));
    return rcpp_result_gen;
END_RCPP
}
// update_Z_m
arma::mat update_Z_m(List inits, List spatial_data);
RcppExport SEXP _RSTr_update_Z_m(SEXP initsSEXP, SEXP spatial_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(update_Z_m(inits, spatial_data));
    return rcpp_result_gen;
END_RCPP
}
// update_G_m
arma::mat update_G_m(List inits, List priors, List spatial_data);
RcppExport SEXP _RSTr_update_G_m(SEXP initsSEXP, SEXP priorsSEXP, SEXP spatial_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type priors(priorsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(update_G_m(inits, priors, spatial_data));
    return rcpp_result_gen;
END_RCPP
}
// update_tau2_m
arma::rowvec update_tau2_m(List inits, List priors, List spatial_data);
RcppExport SEXP _RSTr_update_tau2_m(SEXP initsSEXP, SEXP priorsSEXP, SEXP spatial_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type priors(priorsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(update_tau2_m(inits, priors, spatial_data));
    return rcpp_result_gen;
END_RCPP
}
// update_theta_m
arma::mat update_theta_m(List inits, List data, List priors, List spatial_data, List params, arma::mat& t_accept);
RcppExport SEXP _RSTr_update_theta_m(SEXP initsSEXP, SEXP dataSEXP, SEXP priorsSEXP, SEXP spatial_dataSEXP, SEXP paramsSEXP, SEXP t_acceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< List >::type priors(priorsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type t_accept(t_acceptSEXP);
    rcpp_result_gen = Rcpp::wrap(update_theta_m(inits, data, priors, spatial_data, params, t_accept));
    return rcpp_result_gen;
END_RCPP
}
// update_beta_mst
arma::cube update_beta_mst(List inits, List spatial_data);
RcppExport SEXP _RSTr_update_beta_mst(SEXP initsSEXP, SEXP spatial_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(update_beta_mst(inits, spatial_data));
    return rcpp_result_gen;
END_RCPP
}
// update_Z_mst
arma::cube update_Z_mst(List inits, List spatial_data);
RcppExport SEXP _RSTr_update_Z_mst(SEXP initsSEXP, SEXP spatial_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(update_Z_mst(inits, spatial_data));
    return rcpp_result_gen;
END_RCPP
}
// update_G_mst
arma::cube update_G_mst(List inits, List priors, List spatial_data);
RcppExport SEXP _RSTr_update_G_mst(SEXP initsSEXP, SEXP priorsSEXP, SEXP spatial_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type priors(priorsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(update_G_mst(inits, priors, spatial_data));
    return rcpp_result_gen;
END_RCPP
}
// update_Ag_mst
arma::mat update_Ag_mst(List inits, List priors);
RcppExport SEXP _RSTr_update_Ag_mst(SEXP initsSEXP, SEXP priorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type priors(priorsSEXP);
    rcpp_result_gen = Rcpp::wrap(update_Ag_mst(inits, priors));
    return rcpp_result_gen;
END_RCPP
}
// update_tau2_mst
arma::vec update_tau2_mst(List inits, List priors, List spatial_data);
RcppExport SEXP _RSTr_update_tau2_mst(SEXP initsSEXP, SEXP priorsSEXP, SEXP spatial_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type priors(priorsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(update_tau2_mst(inits, priors, spatial_data));
    return rcpp_result_gen;
END_RCPP
}
// update_theta_mst
arma::cube update_theta_mst(List inits, List data, List priors, List spatial_data, List params, arma::cube& t_accept);
RcppExport SEXP _RSTr_update_theta_mst(SEXP initsSEXP, SEXP dataSEXP, SEXP priorsSEXP, SEXP spatial_dataSEXP, SEXP paramsSEXP, SEXP t_acceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< List >::type priors(priorsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type t_accept(t_acceptSEXP);
    rcpp_result_gen = Rcpp::wrap(update_theta_mst(inits, data, priors, spatial_data, params, t_accept));
    return rcpp_result_gen;
END_RCPP
}
// update_rho_mst
arma::rowvec update_rho_mst(List inits, List priors, List spatial_data, arma::vec& r_accept);
RcppExport SEXP _RSTr_update_rho_mst(SEXP initsSEXP, SEXP priorsSEXP, SEXP spatial_dataSEXP, SEXP r_acceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type priors(priorsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type r_accept(r_acceptSEXP);
    rcpp_result_gen = Rcpp::wrap(update_rho_mst(inits, priors, spatial_data, r_accept));
    return rcpp_result_gen;
END_RCPP
}
// update_Z_ucar
arma::cube update_Z_ucar(List inits, List spatial_data);
RcppExport SEXP _RSTr_update_Z_ucar(SEXP initsSEXP, SEXP spatial_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(update_Z_ucar(inits, spatial_data));
    return rcpp_result_gen;
END_RCPP
}
// update_sig2_ucar
arma::mat update_sig2_ucar(List inits, List spatial_data, List priors);
RcppExport SEXP _RSTr_update_sig2_ucar(SEXP initsSEXP, SEXP spatial_dataSEXP, SEXP priorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    Rcpp::traits::input_parameter< List >::type priors(priorsSEXP);
    rcpp_result_gen = Rcpp::wrap(update_sig2_ucar(inits, spatial_data, priors));
    return rcpp_result_gen;
END_RCPP
}
// update_sig2_ucar_restricted
arma::mat update_sig2_ucar_restricted(List inits, List spatial_data, List params, List priors);
RcppExport SEXP _RSTr_update_sig2_ucar_restricted(SEXP initsSEXP, SEXP spatial_dataSEXP, SEXP paramsSEXP, SEXP priorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< List >::type priors(priorsSEXP);
    rcpp_result_gen = Rcpp::wrap(update_sig2_ucar_restricted(inits, spatial_data, params, priors));
    return rcpp_result_gen;
END_RCPP
}
// update_tau2_ucar
arma::mat update_tau2_ucar(List inits, List spatial_data, List priors);
RcppExport SEXP _RSTr_update_tau2_ucar(SEXP initsSEXP, SEXP spatial_dataSEXP, SEXP priorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    Rcpp::traits::input_parameter< List >::type priors(priorsSEXP);
    rcpp_result_gen = Rcpp::wrap(update_tau2_ucar(inits, spatial_data, priors));
    return rcpp_result_gen;
END_RCPP
}
// update_tau2_ucar_restricted
arma::mat update_tau2_ucar_restricted(List inits, List spatial_data, List params, List priors);
RcppExport SEXP _RSTr_update_tau2_ucar_restricted(SEXP initsSEXP, SEXP spatial_dataSEXP, SEXP paramsSEXP, SEXP priorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< List >::type priors(priorsSEXP);
    rcpp_result_gen = Rcpp::wrap(update_tau2_ucar_restricted(inits, spatial_data, params, priors));
    return rcpp_result_gen;
END_RCPP
}
// update_theta_ucar
arma::cube update_theta_ucar(List inits, List data, List priors, List spatial_data, List params, arma::cube& t_accept);
RcppExport SEXP _RSTr_update_theta_ucar(SEXP initsSEXP, SEXP dataSEXP, SEXP priorsSEXP, SEXP spatial_dataSEXP, SEXP paramsSEXP, SEXP t_acceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< List >::type priors(priorsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type t_accept(t_acceptSEXP);
    rcpp_result_gen = Rcpp::wrap(update_theta_ucar(inits, data, priors, spatial_data, params, t_accept));
    return rcpp_result_gen;
END_RCPP
}
// update_beta_ucar
arma::cube update_beta_ucar(List inits, List spatial_data);
RcppExport SEXP _RSTr_update_beta_ucar(SEXP initsSEXP, SEXP spatial_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(update_beta_ucar(inits, spatial_data));
    return rcpp_result_gen;
END_RCPP
}
// update_beta_ucar_restricted
arma::cube update_beta_ucar_restricted(List inits, List spatial_data, List params);
RcppExport SEXP _RSTr_update_beta_ucar_restricted(SEXP initsSEXP, SEXP spatial_dataSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< List >::type spatial_data(spatial_dataSEXP);
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(update_beta_ucar_restricted(inits, spatial_data, params));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RSTr_get_regs", (DL_FUNC) &_RSTr_get_regs, 2},
    {"_RSTr_get_subregs", (DL_FUNC) &_RSTr_get_subregs, 4},
    {"_RSTr_get_grp", (DL_FUNC) &_RSTr_get_grp, 3},
    {"_RSTr_get_row", (DL_FUNC) &_RSTr_get_row, 3},
    {"_RSTr_Sig_eta_i", (DL_FUNC) &_RSTr_Sig_eta_i, 2},
    {"_RSTr_Sig_eta", (DL_FUNC) &_RSTr_Sig_eta, 1},
    {"_RSTr_cpp_rmvnorm", (DL_FUNC) &_RSTr_cpp_rmvnorm, 2},
    {"_RSTr_geteig", (DL_FUNC) &_RSTr_geteig, 1},
    {"_RSTr_update_beta_m", (DL_FUNC) &_RSTr_update_beta_m, 2},
    {"_RSTr_update_Z_m", (DL_FUNC) &_RSTr_update_Z_m, 2},
    {"_RSTr_update_G_m", (DL_FUNC) &_RSTr_update_G_m, 3},
    {"_RSTr_update_tau2_m", (DL_FUNC) &_RSTr_update_tau2_m, 3},
    {"_RSTr_update_theta_m", (DL_FUNC) &_RSTr_update_theta_m, 6},
    {"_RSTr_update_beta_mst", (DL_FUNC) &_RSTr_update_beta_mst, 2},
    {"_RSTr_update_Z_mst", (DL_FUNC) &_RSTr_update_Z_mst, 2},
    {"_RSTr_update_G_mst", (DL_FUNC) &_RSTr_update_G_mst, 3},
    {"_RSTr_update_Ag_mst", (DL_FUNC) &_RSTr_update_Ag_mst, 2},
    {"_RSTr_update_tau2_mst", (DL_FUNC) &_RSTr_update_tau2_mst, 3},
    {"_RSTr_update_theta_mst", (DL_FUNC) &_RSTr_update_theta_mst, 6},
    {"_RSTr_update_rho_mst", (DL_FUNC) &_RSTr_update_rho_mst, 4},
    {"_RSTr_update_Z_ucar", (DL_FUNC) &_RSTr_update_Z_ucar, 2},
    {"_RSTr_update_sig2_ucar", (DL_FUNC) &_RSTr_update_sig2_ucar, 3},
    {"_RSTr_update_sig2_ucar_restricted", (DL_FUNC) &_RSTr_update_sig2_ucar_restricted, 4},
    {"_RSTr_update_tau2_ucar", (DL_FUNC) &_RSTr_update_tau2_ucar, 3},
    {"_RSTr_update_tau2_ucar_restricted", (DL_FUNC) &_RSTr_update_tau2_ucar_restricted, 4},
    {"_RSTr_update_theta_ucar", (DL_FUNC) &_RSTr_update_theta_ucar, 6},
    {"_RSTr_update_beta_ucar", (DL_FUNC) &_RSTr_update_beta_ucar, 2},
    {"_RSTr_update_beta_ucar_restricted", (DL_FUNC) &_RSTr_update_beta_ucar_restricted, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_RSTr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
