// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_regs
arma::cube get_regs(const arma::cube& arr, const arma::uvec& ind);
RcppExport SEXP _RSTr_get_regs(SEXP arrSEXP, SEXP indSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type ind(indSEXP);
    rcpp_result_gen = Rcpp::wrap(get_regs(arr, ind));
    return rcpp_result_gen;
END_RCPP
}
// get_subregs
arma::vec get_subregs(const arma::cube& arr, const arma::uvec& ind, const arma::uword& grp, const arma::uword& time);
RcppExport SEXP _RSTr_get_subregs(SEXP arrSEXP, SEXP indSEXP, SEXP grpSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type ind(indSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type grp(grpSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_subregs(arr, ind, grp, time));
    return rcpp_result_gen;
END_RCPP
}
// get_grp
arma::vec get_grp(const arma::cube& arr, const arma::uword& reg, const arma::uword& time);
RcppExport SEXP _RSTr_get_grp(SEXP arrSEXP, SEXP regSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type reg(regSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_grp(arr, reg, time));
    return rcpp_result_gen;
END_RCPP
}
// get_subgrp
arma::mat get_subgrp(const arma::cube& arr, const arma::uvec& ind, const arma::uword& time);
RcppExport SEXP _RSTr_get_subgrp(SEXP arrSEXP, SEXP indSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type ind(indSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_subgrp(arr, ind, time));
    return rcpp_result_gen;
END_RCPP
}
// get_row
arma::vec get_row(const arma::cube& arr, const arma::uword& grp, const arma::uword& time);
RcppExport SEXP _RSTr_get_row(SEXP arrSEXP, SEXP grpSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type grp(grpSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_row(arr, grp, time));
    return rcpp_result_gen;
END_RCPP
}
// Sig_eta_i
arma::field<arma::mat> Sig_eta_i(const arma::cube& G, const arma::vec& rho);
RcppExport SEXP _RSTr_Sig_eta_i(SEXP GSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(Sig_eta_i(G, rho));
    return rcpp_result_gen;
END_RCPP
}
// Sig_eta
arma::field<arma::mat> Sig_eta(const arma::field<arma::mat>& Sein);
RcppExport SEXP _RSTr_Sig_eta(SEXP SeinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Sein(SeinSEXP);
    rcpp_result_gen = Rcpp::wrap(Sig_eta(Sein));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rmvnorm
arma::mat cpp_rmvnorm(const arma::vec& mean, const arma::mat& covar);
RcppExport SEXP _RSTr_cpp_rmvnorm(SEXP meanSEXP, SEXP covarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covar(covarSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rmvnorm(mean, covar));
    return rcpp_result_gen;
END_RCPP
}
// geteig
arma::mat geteig(const arma::mat& covar);
RcppExport SEXP _RSTr_geteig(SEXP covarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type covar(covarSEXP);
    rcpp_result_gen = Rcpp::wrap(geteig(covar));
    return rcpp_result_gen;
END_RCPP
}
// update_Ag
void update_Ag(List& RSTr_obj);
RcppExport SEXP _RSTr_update_Ag(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_Ag(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_G_default
void update_G_default(List& RSTr_obj);
RcppExport SEXP _RSTr_update_G_default(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_G_default(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_G_mstcar
void update_G_mstcar(List& RSTr_obj);
RcppExport SEXP _RSTr_update_G_mstcar(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_G_mstcar(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_Z_ucar
void update_Z_ucar(List& RSTr_obj);
RcppExport SEXP _RSTr_update_Z_ucar(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_Z_ucar(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_Z_mcar
void update_Z_mcar(List& RSTr_obj);
RcppExport SEXP _RSTr_update_Z_mcar(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_Z_mcar(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_Z_mstcar
void update_Z_mstcar(List& RSTr_obj);
RcppExport SEXP _RSTr_update_Z_mstcar(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_Z_mstcar(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_beta_default
void update_beta_default(List& RSTr_obj);
RcppExport SEXP _RSTr_update_beta_default(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_beta_default(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_beta_ucar_restricted
void update_beta_ucar_restricted(List& RSTr_obj);
RcppExport SEXP _RSTr_update_beta_ucar_restricted(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_beta_ucar_restricted(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_beta_mstcar
void update_beta_mstcar(List& RSTr_obj);
RcppExport SEXP _RSTr_update_beta_mstcar(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_beta_mstcar(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_lambda
void update_lambda(List& RSTr_obj);
RcppExport SEXP _RSTr_update_lambda(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_lambda(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_rho
void update_rho(List& RSTr_obj);
RcppExport SEXP _RSTr_update_rho(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_rho(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_sig2_default
void update_sig2_default(List& RSTr_obj);
RcppExport SEXP _RSTr_update_sig2_default(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_sig2_default(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_sig2_ucar_restricted
void update_sig2_ucar_restricted(List& RSTr_obj);
RcppExport SEXP _RSTr_update_sig2_ucar_restricted(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_sig2_ucar_restricted(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_tau2_default
void update_tau2_default(List& RSTr_obj);
RcppExport SEXP _RSTr_update_tau2_default(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_tau2_default(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_tau2_ucar_restricted
void update_tau2_ucar_restricted(List& RSTr_obj);
RcppExport SEXP _RSTr_update_tau2_ucar_restricted(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_tau2_ucar_restricted(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_tau2_mstcar
void update_tau2_mstcar(List& RSTr_obj);
RcppExport SEXP _RSTr_update_tau2_mstcar(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_tau2_mstcar(RSTr_obj);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RSTr_get_regs", (DL_FUNC) &_RSTr_get_regs, 2},
    {"_RSTr_get_subregs", (DL_FUNC) &_RSTr_get_subregs, 4},
    {"_RSTr_get_grp", (DL_FUNC) &_RSTr_get_grp, 3},
    {"_RSTr_get_subgrp", (DL_FUNC) &_RSTr_get_subgrp, 3},
    {"_RSTr_get_row", (DL_FUNC) &_RSTr_get_row, 3},
    {"_RSTr_Sig_eta_i", (DL_FUNC) &_RSTr_Sig_eta_i, 2},
    {"_RSTr_Sig_eta", (DL_FUNC) &_RSTr_Sig_eta, 1},
    {"_RSTr_cpp_rmvnorm", (DL_FUNC) &_RSTr_cpp_rmvnorm, 2},
    {"_RSTr_geteig", (DL_FUNC) &_RSTr_geteig, 1},
    {"_RSTr_update_Ag", (DL_FUNC) &_RSTr_update_Ag, 1},
    {"_RSTr_update_G_default", (DL_FUNC) &_RSTr_update_G_default, 1},
    {"_RSTr_update_G_mstcar", (DL_FUNC) &_RSTr_update_G_mstcar, 1},
    {"_RSTr_update_Z_ucar", (DL_FUNC) &_RSTr_update_Z_ucar, 1},
    {"_RSTr_update_Z_mcar", (DL_FUNC) &_RSTr_update_Z_mcar, 1},
    {"_RSTr_update_Z_mstcar", (DL_FUNC) &_RSTr_update_Z_mstcar, 1},
    {"_RSTr_update_beta_default", (DL_FUNC) &_RSTr_update_beta_default, 1},
    {"_RSTr_update_beta_ucar_restricted", (DL_FUNC) &_RSTr_update_beta_ucar_restricted, 1},
    {"_RSTr_update_beta_mstcar", (DL_FUNC) &_RSTr_update_beta_mstcar, 1},
    {"_RSTr_update_lambda", (DL_FUNC) &_RSTr_update_lambda, 1},
    {"_RSTr_update_rho", (DL_FUNC) &_RSTr_update_rho, 1},
    {"_RSTr_update_sig2_default", (DL_FUNC) &_RSTr_update_sig2_default, 1},
    {"_RSTr_update_sig2_ucar_restricted", (DL_FUNC) &_RSTr_update_sig2_ucar_restricted, 1},
    {"_RSTr_update_tau2_default", (DL_FUNC) &_RSTr_update_tau2_default, 1},
    {"_RSTr_update_tau2_ucar_restricted", (DL_FUNC) &_RSTr_update_tau2_ucar_restricted, 1},
    {"_RSTr_update_tau2_mstcar", (DL_FUNC) &_RSTr_update_tau2_mstcar, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RSTr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
