# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_regs <- function(arr, ind) {
    .Call(`_RSTr_get_regs`, arr, ind)
}

get_subregs <- function(arr, ind, grp, time) {
    .Call(`_RSTr_get_subregs`, arr, ind, grp, time)
}

get_grp <- function(arr, reg, time) {
    .Call(`_RSTr_get_grp`, arr, reg, time)
}

get_subgrp <- function(arr, ind, time) {
    .Call(`_RSTr_get_subgrp`, arr, ind, time)
}

get_row <- function(arr, grp, time) {
    .Call(`_RSTr_get_row`, arr, grp, time)
}

Sig_eta_i <- function(G, rho) {
    .Call(`_RSTr_Sig_eta_i`, G, rho)
}

Sig_eta <- function(Sein) {
    .Call(`_RSTr_Sig_eta`, Sein)
}

cpp_rmvnorm <- function(mean, covar) {
    .Call(`_RSTr_cpp_rmvnorm`, mean, covar)
}

geteig <- function(covar) {
    .Call(`_RSTr_geteig`, covar)
}

update_Ag <- function(initial_values, priors) {
    .Call(`_RSTr_update_Ag`, initial_values, priors)
}

update_beta_ucar <- function(initial_values, spatial_data) {
    .Call(`_RSTr_update_beta_ucar`, initial_values, spatial_data)
}

update_beta_ucar_restricted <- function(initial_values, spatial_data, params) {
    .Call(`_RSTr_update_beta_ucar_restricted`, initial_values, spatial_data, params)
}

update_beta_mstcar <- function(initial_values, spatial_data) {
    .Call(`_RSTr_update_beta_mstcar`, initial_values, spatial_data)
}

update_G_mcar <- function(initial_values, spatial_data, priors) {
    .Call(`_RSTr_update_G_mcar`, initial_values, spatial_data, priors)
}

update_G_mstcar <- function(initial_values, spatial_data, priors) {
    .Call(`_RSTr_update_G_mstcar`, initial_values, spatial_data, priors)
}

update_rho <- function(initial_values, spatial_data, priors, r_accept) {
    .Call(`_RSTr_update_rho`, initial_values, spatial_data, priors, r_accept)
}

update_sig2_ucar <- function(initial_values, spatial_data, priors) {
    .Call(`_RSTr_update_sig2_ucar`, initial_values, spatial_data, priors)
}

update_sig2_ucar_restricted <- function(initial_values, spatial_data, priors, params) {
    .Call(`_RSTr_update_sig2_ucar_restricted`, initial_values, spatial_data, priors, params)
}

update_tau2_ucar <- function(initial_values, spatial_data, priors) {
    .Call(`_RSTr_update_tau2_ucar`, initial_values, spatial_data, priors)
}

update_tau2_ucar_restricted <- function(initial_values, spatial_data, priors, params) {
    .Call(`_RSTr_update_tau2_ucar_restricted`, initial_values, spatial_data, priors, params)
}

update_tau2_mstcar <- function(initial_values, spatial_data, priors) {
    .Call(`_RSTr_update_tau2_mstcar`, initial_values, spatial_data, priors)
}

update_lambda <- function(initial_values, spatial_data, priors, params, data, t_accept) {
    .Call(`_RSTr_update_lambda`, initial_values, spatial_data, priors, params, data, t_accept)
}

update_Z_ucar <- function(initial_values, spatial_data) {
    .Call(`_RSTr_update_Z_ucar`, initial_values, spatial_data)
}

update_Z_mcar <- function(initial_values, spatial_data) {
    .Call(`_RSTr_update_Z_mcar`, initial_values, spatial_data)
}

update_Z_mstcar <- function(initial_values, spatial_data) {
    .Call(`_RSTr_update_Z_mstcar`, initial_values, spatial_data)
}

