# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_regs <- function(arr, ind) {
    .Call(`_RSTr_get_regs`, arr, ind)
}

get_subregs <- function(arr, ind, grp, time) {
    .Call(`_RSTr_get_subregs`, arr, ind, grp, time)
}

get_grp <- function(arr, reg, time) {
    .Call(`_RSTr_get_grp`, arr, reg, time)
}

get_subgrp <- function(arr, ind, time) {
    .Call(`_RSTr_get_subgrp`, arr, ind, time)
}

get_row <- function(arr, grp, time) {
    .Call(`_RSTr_get_row`, arr, grp, time)
}

Sig_eta_i <- function(G, rho) {
    .Call(`_RSTr_Sig_eta_i`, G, rho)
}

Sig_eta <- function(Sein) {
    .Call(`_RSTr_Sig_eta`, Sein)
}

cpp_rmvnorm <- function(mean, covar) {
    .Call(`_RSTr_cpp_rmvnorm`, mean, covar)
}

geteig <- function(covar) {
    .Call(`_RSTr_geteig`, covar)
}

update_Ag <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_Ag`, RSTr_obj))
}

update_G_default <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_G_default`, RSTr_obj))
}

update_G_mstcar <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_G_mstcar`, RSTr_obj))
}

update_Z_ucar <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_Z_ucar`, RSTr_obj))
}

update_Z_mcar <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_Z_mcar`, RSTr_obj))
}

update_Z_mstcar <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_Z_mstcar`, RSTr_obj))
}

update_beta_default <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_beta_default`, RSTr_obj))
}

update_beta_ucar_restricted <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_beta_ucar_restricted`, RSTr_obj))
}

update_beta_mstcar <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_beta_mstcar`, RSTr_obj))
}

update_lambda <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_lambda`, RSTr_obj))
}

update_rho <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_rho`, RSTr_obj))
}

update_sig2_default <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_sig2_default`, RSTr_obj))
}

update_sig2_ucar_restricted <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_sig2_ucar_restricted`, RSTr_obj))
}

update_tau2_default <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_tau2_default`, RSTr_obj))
}

update_tau2_ucar_restricted <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_tau2_ucar_restricted`, RSTr_obj))
}

update_tau2_mstcar <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_tau2_mstcar`, RSTr_obj))
}

